#name: Duckstar Dev CI/CD
#
#on:
#  push:
#    branches: [ dev ]  # dev ë¸Œëœì¹˜ì— pushê°€ ì¼ì–´ë‚  ë•Œ ì‹¤í–‰
#
#jobs:
#  build:
#    runs-on: ubuntu-latest # OS í™˜ê²½
#
#    steps:
#      - uses: actions/checkout@v3  # ì €ì¥ì†Œ ì½”ë“œ ì²´í¬ì•„ì›ƒ
#
#      - name: Set up JDK 17  # Java ê°œë°œ í‚· ì„¤ì •
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: '17'
#
#      - name: Set environment variables
#        run: |
#          echo "BASE_URL=https://duckstar.kr" >> $GITHUB_ENV
#
#      - name: Make application.yml  # application.yml íŒŒì¼ ìƒì„± ë° í™˜ê²½ ë³€ìˆ˜ ì ìš©
#        run: |
#          cd ./src/main/resources
#          echo "${{ secrets.APPLICATION_YML }}" > ./application.yml
#          cat ./application.yml | envsubst > ./application.yml.tmp && mv ./application.yml.tmp ./application.yml
#        shell: bash
#
#      - name: Grant execute permission for gradlew  # gradlew ì‹¤í–‰ ê¶Œí•œ ë¶€ì—¬
#        run: chmod +x gradlew
#
#      - name: Clean and Build with Gradle  # Gradle clean build ì‹¤í–‰
#        uses: gradle/gradle-build-action@v3
#        with:
#          arguments: clean build --stacktrace --info --scan  # ğŸ”¹ ìì„¸í•œ ë¡œê·¸ ì¶œë ¥
#          cache-read-only: false  # Gradle ë¹Œë“œ ìºì‹œ í™œì„±í™” (ë¹Œë“œ ì†ë„ ìµœì í™”)
#
#
#      - name: Upload Test Report  # ğŸ”¹ í…ŒìŠ¤íŠ¸ ë¦¬í¬íŠ¸ ì—…ë¡œë“œ
#        if: failure()  # í…ŒìŠ¤íŠ¸ ì‹¤íŒ¨ ì‹œì—ë§Œ ì‹¤í–‰
#        uses: actions/upload-artifact@v4
#        with:
#          name: test-report
#          path: build/reports/tests/test/
#
#
#      - name: Upload build artifact  # ë¹Œë“œëœ ì•„í‹°íŒ©íŠ¸ ì—…ë¡œë“œ
#        uses: actions/upload-artifact@v4
#        with:
#          name: duckstar-server
#          path: build/libs/*.jar
#
#  deploy:
#    needs: build
#    if: success()  # ğŸ”¹ ë¹Œë“œ ì„±ê³µ ì‹œì—ë§Œ ì‹¤í–‰ë˜ë„ë¡ ì¶”ê°€
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Download build artifact  # ì´ì „ ë‹¨ê³„ì—ì„œ ì—…ë¡œë“œí•œ ì•„í‹°íŒ©íŠ¸ ë‹¤ìš´ë¡œë“œ
#        uses: actions/download-artifact@v4
#        with:
#          name: duckstar-server
#          path: build/libs/
#
#      - name: Deploy to EC2  # EC2ì— ë°°í¬
#        env:
#          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
#          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
#          EC2_HOST: ${{ secrets.EC2_HOST }}
#        run: |
#          echo "$EC2_SSH_KEY" > private_key.pem
#          chmod 600 private_key.pem
#
#          jar_file=$(find build/libs -name '*.jar' ! -name '*plain.jar' | head -n 1)
#
#          scp -i private_key.pem -o StrictHostKeyChecking=no "$jar_file" $EC2_USERNAME@$EC2_HOST:/home/$EC2_USERNAME/duckstar-server.jar
#
#          ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_HOST "
#            pgrep -f duckstar-server.jar | xargs -r kill -15
#            sleep 10
#            mkdir -p /home/$EC2_USERNAME/logs
#            nohup java -jar /home/$EC2_USERNAME/duckstar-server.jar > /home/$EC2_USERNAME/logs/app.log 2>&1 &
#          "
#
#          rm -f private_key.pem